// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export * from '../exports'
export * from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_afp74kv5iscgr7eduxuo4xlpkq/node_modules/dumi/dist/client/theme-api/index.js'
