// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export {
	createBrowserHistory,
	createHashHistory,
	createMemoryHistory,
	createSearchParams,
	generatePath,
	matchPath,
	matchRoutes,
	Navigate,
	NavLink,
	Outlet,
	resolvePath,
	useLocation,
	useMatch,
	useNavigate,
	useOutlet,
	useOutletContext,
	useParams,
	useResolvedPath,
	useRoutes,
	useSearchParams,
	Helmet,
	useAppData,
	useSelectedRoutes,
	useClientLoaderData,
	useServerLoaderData,
	renderClient,
	__getRoot,
	Link,
	useRouteData,
	__useFetcher,
	withRouter
} from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.51_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
export type { History } from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+@umijs+renderer-react@4.0.51_ef5jwxihqo6n7gxfmzogljlgcm/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export {
	ApplyPluginsType,
	PluginManager
} from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+umi@4.0.51_rdgvyipbmv3sg47flosry4j3ou/node_modules/umi/client/client/plugin.js'
export { history, createHistory } from './core/history'
export { terminal } from './core/terminal'
export { TestBrowser } from './testBrowser'
// plugins
// plugins types.d.ts
