// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react'
import { useOutlet, history } from 'dumi'
import { SiteContext } from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_vvffjg2wgcblwf7llftpu7dopm/node_modules/dumi/dist/client/theme-api/context.js'
import { demos, components } from '../meta'
import { locales } from '../locales/config'

const entryExports = {}

export default function DumiContextWrapper() {
	const outlet = useOutlet()
	const [loading, setLoading] = useState(true)
	const prev = useRef(history.location.pathname)

	useEffect(() => {
		return history.listen((next) => {
			if (next.location.pathname !== prev.current) {
				prev.current = next.location.pathname

				// mark loading when route change, page component will set false when loaded
				setLoading(true)

				// scroll to top when route changed
				document.documentElement.scrollTo(0, 0)
			}
		})
	}, [])

	return (
		<SiteContext.Provider
			value={{
				pkg: {
					name: 'perfect-design',
					description: '',
					version: '1.0.0',
					license: 'ISC',
					author: ''
				},
				entryExports,
				demos,
				components,
				locales,
				loading,
				setLoading,
				themeConfig: {
					title: 'Perfect Design',
					footer:
						'Copyright © 2022-2022 Perfect Design. All Rights Reserved. Perfect Design 版权所有. 苏ICP备2022018060号',
					prefersColor: { default: 'light', switch: true },
					name: 'Perfect D',
					carrier: 'dumi',
					hd: true,
					rtl: true,
					nav: [
						{ title: '指南', link: '/guide' },
						{ title: '组件', link: '/components/alert' }
					]
				}
			}}
		>
			{outlet}
		</SiteContext.Provider>
	)
}
