// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/kkkkkk/Desktop/Development/perfect-design/node_modules/.pnpm/registry.npmmirror.com+dumi@2.1.9_26bkyrclqv5t5br4pab7hogptq/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
